### ISSUE TITLE
 RpiGpioSetup V4.2 not compatible

### ISSUE THREAD

**Issue by Gexle** [kwindrem/RpiGpioSetup#19]
Hello Kevin

I updated RpiGpioSetup and after the update it said that it was no longer compatible with version V2.93...

Can you please fix this so that I can use RpiGpioSetup again please!

I hope it's not all gone now so my settings

Use RpiGipo for fan control..

The other updates all worked!

The V2.93 runs wonderfully, so I would like to stay with the V2.93
Please help

**Comment by Gexle** [comment]
I made a backup beforehand.

If it works again with version V4.2, can I restore the backup or??

**Comment by kwindrem** [comment]
You can set the branch/tag to v4.2 to get back to the older version. 

I find this odd since I've made no changes in the file sets for older versions. If you can get to the logs I'd very much like to see /data/log/SetupHelper where the errors are displayed. It will take me a while to load v2.93 on my test system.

**Comment by kwindrem** [comment]
Forget my request for logs. I have identified the problem and working on a fix now.

**Comment by kwindrem** [comment]
Fixed in RpiGpioSetup v4.3 and RpiDisplaySetup v3.7.
